name: "CLA Assistant 2.0"
on:
  issue_comment:
    types: [created, edited]

jobs:
  CLA_Assistant:
    # This job only runs for pull request comments
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR comment"
        if: github.event.issue.pull_request && (github.event.comment.body == '@cla-pls' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA')
        uses: contributor-assistant/github-action@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_SCOPE }}
        with:
          path-to-document: "https://github.com/juggernot325/strange_wall/blob/master/ICLA.md"
